export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const LOGOUT = 'LOGOUT'
export const ERROR_MSG = 'ERROR_MSG'
export const GET_USER = 'GET_USER'
export const REQUEST_START = 'REQUEST_START'
export const REQUEST_STOP = 'REQUEST_STOP'